#!/bin/bash

TIME=$HOME/dev/cryptoverif/xtime
CV="$HOME/dev/cryptoverif/cryptoverif -lib tls-lib"

# The argument of analyze is
# $1 = file name (without .cv)

function analyze()
{
echo $1
$TIME $CV $1.cv > $1.out
tail -n 2 $1.out
}

analyze HKDFexpand
analyze KeySchedule1
analyze KeySchedule2
analyze KeySchedule3
analyze tls13-core-InitialHandshake-LeakKeysIfCorrupted
analyze tls13-core-InitialHandshake-SecrecyServerSide
analyze tls13-core-InitialHandshake-Secrecy0.5RTT
analyze tls13-core-PSKandPSKDHE-NoCorruption
analyze tls13-core-RecordProtocol

